### ISSUE TITLE
Provide a function to show the weather forecast in the minibuffer [Feature request]

### ISSUE THREAD

**Issue by kaushalmodi** [aaronbieber/sunshine.el#2]
Thanks for developing this package. 

It would be great to have a minimal mode when something like `M-x sunshine-forecast-quick` shows the forecast info in the minibuffer.

**Comment by aaronbieber** [comment]
Maybe like a two-day forecast? I did some experiments displaying multi-line formatted text in the minibuffer with a huge `(message)` call and it seems to work so I will hack away at this.

I will need to refactor a lot of the code so that I can carry the desired display type through the asynchronous `url-retrieve` callback and branch at the point where I normally create the window and do the drawing. Definitely doable, though.

**Comment by aaronbieber** [comment]
I am actively working on this "quick forecast" feature. Coming very soon.

**Comment by kaushalmodi** [comment]
Great! Thank you.

**Comment by aaronbieber** [comment]
This new feature is merged into master. Call `sunshine-quick-forecast` to see a two-day forecast in the minibuffer.

More can be done to make it look better, and three days can probably fit without a problem. The code should be cleaned up a bit before adding any of that, but it can be done. Or feel free to take a stab at it yourself; all of the action happens in `sunshine-draw-quick-forecast`.
